Matiasjj/deployed version
lvarin/template-hedgedoc-openshift pull request #1
Opened 2022-11-10 12:25 UTC by MatiasJJ

Here in the deployment version there are some changes that we made during the setup. I would like to have those in the template as well. Also I added 
```
- name: CMD_ALLOW_FREEURL
              value: 'true'
```
which I think is relevant also.

2022-11-11 11:59 UTC, lvarin commented on hedgedoc-deployment.yml
> +apiVersion: apps/v1
This file should not be here

2022-11-11 12:23 UTC, MatiasJJ commented on hedgedoc-deployment.yml
> +apiVersion: apps/v1
```suggestion

```

2022-11-11 13:53 UTC, lvarin requested changes
If the file is removed, I will approve the PR

2022-11-11 13:53 UTC, lvarin commented on hedgedoc-deployment.yml
> +  updatedReplicas: 1
I meant the whole file

2022-11-11 13:53 UTC, lvarin commented on hedgedoc-deployment.yml
> +  updatedReplicas: 1
This whole file must be removed

2022-11-16 07:17 UTC, MatiasJJ commented on hedgedoc-deployment.yml
> +  updatedReplicas: 1
Yes now I see

2022-11-16 08:53 UTC, lvarin approved these changes
LGTM

2022-11-16 08:54 UTC, merged